### ISSUE TITLE
NoMeta error getting packages with v>0.2.2

### ISSUE THREAD

**Issue by gnattishness** [bwplotka/bingo#39] opened 2020-07-02 08:22 UTC
Hello,
I seem to be getting NoMeta errors whenever running `bingo get` (for any package) with bingo v0.2.2 or greater.
See below for steps to reproduce:
```console
# docker run -it golang:1.14.2-buster /bin/bash
# go version
go version go1.14.2 linux/amd64
# export GO111MODULE=on && export GOBIN="$HOME/.bin" && export PATH="$GOBIN:$PATH"
# go get -u github.com/bwplotka/bingo@v0.2.3
# bingo get github.com/golangci/golangci-lint/cmd/golangci-lint
Bingo not used before here, creating directory for pinned modules for you at .bingo
go: downloading github.com/golangci/golangci-lint v1.27.0
go: found github.com/golangci/golangci-lint/cmd/golangci-lint in github.com/golangci/golangci-lint v1.27.0
go: downloading github.com/spf13/cobra v0.0.5
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/go-critic/go-critic v0.4.1
go: downloading github.com/go-lintpack/lintpack v0.5.2
go: downloading github.com/spf13/pflag v1.0.5
...
Error: get command failed: get: 0: getting : get direct package: bingo: Go Module without bingo's metadata


# bingo get -v github.com/golangci/golangci-lint/cmd/golangci-lint
exec 'go mod init -modfile=/go/.bingo/golangci-lint.tmp.mod _'
go: found github.com/golangci/golangci-lint/cmd/golangci-lint in github.com/golangci/golangci-lint v1.27.0
exec 'go get -modfile=/go/.bingo/golangci-lint.tmp.mod -d github.com/golangci/golangci-lint/cmd/golangci-lint'
exec 'go list -modfile=/go/.bingo/golangci-lint.tmp.mod -f={{.Name}} github.com/golangci/golangci-lint/cmd/golangci-lint'
Error: bingo: Go Module without bingo's metadata
github.com/bwplotka/bingo/pkg/bingo.init
        /go/src/github.com/bwplotka/bingo/pkg/bingo/mod.go:40
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5414
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5409
runtime.main
        /usr/local/go/src/runtime/proc.go:190
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
get direct package
main.getOne
        /go/src/github.com/bwplotka/bingo/get.go:265
main.get
        /go/src/github.com/bwplotka/bingo/get.go:173
main.main.func2
        /go/src/github.com/bwplotka/bingo/main.go:140
main.main.func5
        /go/src/github.com/bwplotka/bingo/main.go:237
github.com/oklog/run.(*Group).Run.func1
        /go/src/github.com/oklog/run/group.go:38
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
0: getting
main.get
        /go/src/github.com/bwplotka/bingo/get.go:174
main.main.func2
        /go/src/github.com/bwplotka/bingo/main.go:140
main.main.func5
        /go/src/github.com/bwplotka/bingo/main.go:237
github.com/oklog/run.(*Group).Run.func1
        /go/src/github.com/oklog/run/group.go:38
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
get
main.main.func2
        /go/src/github.com/bwplotka/bingo/main.go:149
main.main.func5
        /go/src/github.com/bwplotka/bingo/main.go:237
github.com/oklog/run.(*Group).Run.func1
        /go/src/github.com/oklog/run/group.go:38
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
get command failed
main.main
        /go/src/github.com/bwplotka/bingo/main.go:245
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
```

**Comment by sevein** [comment] 2020-11-23 13:45
I had this same issue today, using Go1.15. Reproducing consistently with:

    docker run -it golang:1.15.5-buster /bin/bash
    export GO111MODULE=on && export GOBIN="$HOME/.bin" && export PATH="$GOBIN:$PATH"
    go get -u github.com/bwplotka/bingo@v0.2.3
    bingo get github.com/golangci/golangci-lint/cmd/golangci-lint

Somehow the following works, but I can't really explain why:

    docker run -it golang:1.15.5-buster /bin/bash
    export GO111MODULE=on && export GOBIN="$HOME/.bin" && export PATH="$GOBIN:$PATH"
    git clone https://github.com/bwplotka/bingo && cd bingo && go install
    bingo get github.com/golangci/golangci-lint/cmd/golangci-lint

@bwplotka, do you have any idea of why this could be happening?

**Comment by bwplotka** [comment] 2020-11-23 13:50
Interesting (: Will take a look, looks like installation path matters? :thinking:

**Comment by bwplotka** [comment] 2021-01-13 21:40
Let's close this for now. What we could try next time this happens is `-u` or  `-upatch` bingo options. Without those `go get` underneath is picking some cached garbage from current `gopath`. Let's try to repro with 0.3.0 (: 

https://github.com/bwplotka/bingo/releases/tag/v0.3.0

**Comment by bwplotka** [comment] 2021-01-13 21:40
Let's reopen if seen again.

**Closed by bwplotka** 2021-01-13 21:40 UTC
